#!/usr/bin/env bash
# Short fix for Nginx port 80 issue
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
service nginx start
kill "$(pgrep nginx | head -1)"

