#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

function clean() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;clean" SIGTERM
trap "echo Y U no love me?!;clean" SIGINT
trap "clean" SIGQUIT

echo $$ >> /var/run/myscript.pid
while [ true ]; do
    echo To infinity and beyond;
    sleep 2
done
